### ISSUE TITLE
No train.py?

### ISSUE THREAD

**Issue by wenxinss** [Gatedip/GDIP-Yolo#1]
no train.py?

**Comment by sanketkalwar** [comment]
@wenxinss, this work is a funded project, so we have only released evaluation and inference scripts for now. We shall release the training script in the future. However, for now, you can follow the implementation details for training from the paper. As we have provided the class for GDIP-Yolo, importing it along with the hyperparameters mentioned in the paper should work.
Let me know if you need any help with that. Closing the issue as of now.
