### ISSUE TITLE
when do the full code that includes training scripts release in the future?

### ISSUE THREAD

**Issue by chriszxk** [Gatedip/GDIP-Yolo#4]
Hi:

Thank you provide a excellent work for us as a reference.

May we know when do the full code that includes training scripts release in the future?

Best regards.
chris

**Comment by Dhruv2012** [comment]
Hii @chriszxk, Apologies for the late reply. 

Being a funded project, there are no current plans from the company to release the training script (we may release it in the future). However, for now, you can follow the implementation details for training from the paper. As we have provided the class for GDIP-Yolo, importing it along with the hyperparameters mentioned in the paper should work. Let me know if you need any help. Hope this helps! Closing the issue as of now.
